Rubrica telefonica/Rubrica telefonica/Models/Contatto.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Rubrica_telefonica.Database
{
    public partial class Contatto
    {
        [NotMapped]
       public string? NumeroTelefono { get; set; }
    }
}

Rubrica telefonica/Rubrica telefonica/Models/ErrorViewModel.cs
namespace Rubrica_telefonica.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rubrica telefonica/Rubrica telefonica/Controllers/ChiamataController.cs
using Microsoft.AspNetCore.Mvc;
using Rubrica_telefonica.DAO;
using Rubrica_telefonica.Database;

namespace Rubrica_telefonica.Controllers
{
    public class ChiamataController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        DaoChiamata daoChia = new DaoChiamata(new CorsoRoma2022Context());
        DaoContatto daoCont = new DaoContatto(new CorsoRoma2022Context());
        [HttpPost]
        public IActionResult Start(int idChiamante, string numeroRicevente)
        {
            Chiamatum chiam = daoChia.StartChiamata(idChiamante, numeroRicevente);
            if (daoCont.checkContatto(idChiamante, chiam.IdRicevente) == true) {
                Contatto cont = daoCont.GetContatto(chiam.IdRicevente, chiam.IdChiamante);
                ViewData["contatto"] = cont;
            }
            return View(chiam);
        }
        [HttpPost]
        public string End(int idChiamata)
        {
            try
            {
                Chiamatum chia = daoChia.EndChiamata(idChiamata);
                return "Success";
            }catch(Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return "Error";
            }
        }
    }
}

Rubrica telefonica/Rubrica telefonica/Controllers/ContattoController.cs
using Microsoft.AspNetCore.Mvc;
using Rubrica_telefonica.DAO;
using Rubrica_telefonica.Database;
using Rubrica_telefonica.Utility;

namespace Rubrica_telefonica.Controllers
{
    public class ContattoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

       DaoContatto d = new DaoContatto(new CorsoRoma2022Context());
        DaoNumero dNumero = new DaoNumero(new CorsoRoma2022Context());


       [HttpGet]
        public IActionResult Edit(int IdContatto)
        {
            var numero = Serializzazione.DeSerialize<Numero>(HttpContext.Session.GetString("Numero"));
           var contatto= d.GetContatto(IdContatto, numero.IdNumero);
            return View(contatto);
        }
        [HttpPost]
        public IActionResult Edit(Contatto contatto, string Cellulare)
        {
            ViewBag.Errore = "Errore nella modifica del contatto";
            return  d.EditContatto(contatto, Cellulare) ? RedirectToAction("Contatti","Home") : View("Edit");

        }
        /*  fatta matteo uguale nell index
        public IActionResult Contatti()
        {
            if (HttpContext.Session.GetString("Numero") != null)
            {
                // HttpContext.Session.SetString("Numero", Serializzazione.Serialize(numero));
                var numero = Serializzazione.DeSerialize<Numero>(HttpContext.Session.GetString("Numero"));
               var contatti= d.GetContatti(numero.IdNumero);
                return View(contatti);
            }
            else
            {
                return View("Login");
            }
        }
        */


        [HttpGet]
        public IActionResult Aggiungi()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Aggiungi(Contatto contatto, string Cellulare)
        {

            if (HttpContext.Session.GetString("Numero") != null)
            {
                Numero numero = Serializzazione.DeSerialize<Numero>(HttpContext.Session.GetString("Numero"));
                contatto.IdPropietario = numero.IdNumero;

                var cellulare = dNumero.CheckNumero(Cellulare);
                contatto.IdCellulare = cellulare.IdNumero;
                ViewBag.Succes = "Errore nell'aggiuta del contatto";
                return d.AddContatto(contatto) ? RedirectToAction("Contatti", "Home") : View("Aggiungi");
            }
            else
            {
                return View("Index", "Home");
            }
        }

        public IActionResult Remove(int idContatto)
        {
            var numero = Serializzazione.DeSerialize<Numero>(HttpContext.Session.GetString("Numero"));
            d.RemoveContatto(idContatto, numero.IdNumero);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Dettaglio(int IdContatto)
        {
            var numero = Serializzazione.DeSerialize<Numero>(HttpContext.Session.GetString("Numero"));

            return d.GetContattoInclude(IdContatto, numero.IdNumero) != null ? View(d.GetContattoInclude(IdContatto, numero.IdNumero)) : RedirectToAction("Contatti", "Home");
        }
    }
}

Rubrica telefonica/Rubrica telefonica/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Rubrica_telefonica.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Rubrica_telefonica.DAO;
using Rubrica_telefonica.Database;
using Rubrica_telefonica.Utility;

namespace Rubrica_telefonica.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        DaoNumero daoNum = new DaoNumero(new CorsoRoma2022Context());
        DaoContatto daoCont = new DaoContatto(new CorsoRoma2022Context());
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public string Login(string numerotelefono)
        {
            var num = Serializzazione.Serialize(daoNum.CheckNumero(numerotelefono));
            HttpContext.Session.SetString("Numero",num);
            return num;
        }
        public IActionResult Contatti()
        {
            var Numero = HttpContext.Session.GetString("Numero");
            if (Numero != null)
            {
                Numero num = Serializzazione.DeSerialize<Numero>(Numero);
                
                return View(daoCont.GetContatti(num.IdNumero));
            }
            else
            {
                return View();
            }
            
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rubrica telefonica/Rubrica telefonica/Views/Chiamata/Index.cshtml
@model Rubrica_telefonica.Database.Chiamatum
@using Rubrica_telefonica.Database
@{
    ViewData["Title"] = "Chiamata";
    var cont = ViewData["contatto"] as Contatto;
}
<style>
    .chiamata {
        width: auto;
        min-width: fit-content;
        max-width: 100%;
        height: auto;
        min-height: fit-content;
        max-height: 100%;
        text-align: center;
    }

    .termina {
        background-color: red;
    }
</style>

<div id="call" class="chiamata">
    @if (cont != null)
    {
        <img src="@cont.Img" />
    }
    else
    {
        <i class="bi bi-person"></i>
    }
    <p id="timer"></p>
    <button id="end" class="termina">Termina</button>
</div>
<script>
    $("end").click(function() {
        $.ajax({
            type: "post",
            url: @Url.Action("End","Chiamata"),
            data: {
                idChiamata = @Model.IdChiamata
                            },
            dataType: "text",
            success: function(data) {
                window.location.href = "@Url.Action("Contatti","Home")"
            }, error(req, status, error) {
                console.log(error);
                alert("Cannot contact databse");
            }
        })
    });

    var ore = 0;
    var minuti = 0;
    var secondi = 0;
    $("timer").setInterval(function() {
        if (secondi < 10) {
            secondi = `0${secondi}`;
        }
        if(minuti < 10){
            minuti = `0${minuti}`;
        }
        if (ore < 10) {
            ore = `0${ore}`;
        }
        secondi++;
        $("timer").innerHTML = ore + ":" + minuti + ":" + secondi
        if(secondi == 59){
            minuti++;
            secondi = 0;
        }
        if (minuti == 59) {
            ore++;
            minuti = 0;
            secondi = 0;
        }
    }, 1000);
</script>

Rubrica telefonica/Rubrica telefonica/Views/Contatto/Aggiungi.cshtml
@using static Rubrica_telefonica.Database.Contatto

<style>

        body {
  background-color: #cccccc !important;
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}

.contact-form-wrapper {
  padding: 100px 0;
}

.contact-form {
  padding: 30px 40px;
  background-color: white;
  border-radius: 12px;
  max-width: 400px;
}

.contact-form textarea {
  resize: none;
}

.contact-form .form-input,
.form-text-area {
  background-color: #ffffff;
  height: 50px;
  padding-left: 16px;
}

.contact-form .form-text-area {
  background-color: #ffffff;
  height: auto;
  padding-left: 16px;
}

.contact-form .form-control::placeholder {
  color: gray;
  font-weight: 500;
  opacity: 1;
}

.contact-form .form-control:-ms-input-placeholder {
  color: gray;
  font-weight: 500;
}

.contact-form .form-control::-ms-input-placeholder {
  color: red;
  font-weight: 500;
}

.contact-form .form-control:focus {
  border-color: #660000;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.07), 0 0 8px black;
}

.contact-form .title {
  text-align: center;
  font-size: 24px;
  font-weight: 500;
}

.contact-form .description {
  color: black;
  font-size: 14px;
  text-align: center;
}

.contact-form .submit-button-wrapper {
  text-align: center;
}

.contact-form .submit-button-wrapper input {
  border: none;
  border-radius: 4px;
  background-color: #b30000;
  color: white;
  text-transform: uppercase;
  padding: 10px 60px;
  font-weight: 500;
  letter-spacing: 2px;
}

.contact-form .submit-button-wrapper input:hover {
  background-color: #660000;
}

    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <div>
  <div class="contact-form-wrapper d-flex justify-content-center">

    <form action="Aggiungi" class="contact-form" method="post" id="addForm" name="addForm">

      <h5 class="title">Aggiungi contatto</h5>
      <p class="description">Inserire qui i dati del nuovo contatto
      </p>
      <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input"  name="Nome" id="Nome" placeholder="Nome" >
      </div>
       <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Cognome" placeholder="Cognome" required>
      </div>
             <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Alias" placeholder="Alias" >
      </div>
       <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Cellulare" placeholder="Cellulare"  maxlength="10" required>
      </div>
       <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Fisso" placeholder="Fisso" maxlength="10" >
      </div>
            <div>
        <input type="email" class="form-control rounded border-white mb-3 form-input" placeholder="Email" name="Email" >

      </div>
       
      <div class="submit-button-wrapper">
        <input type="submit" value="Salva" id="Crea">
      </div>
    </form>
  </div>
</div>

 <script>
    $(document).ready(function() {
    
    $("#addForm").validate({
        rules: {
            Nome: "required"
        },
        messages: {
            Nome: "metti il nome ooooooo"

        }
    })

});


 </script>

Rubrica telefonica/Rubrica telefonica/Views/Contatto/Dettaglio.cshtml
@model Rubrica_telefonica.Database.Contatto



    <label>@Model.Nome</label>
    <label>@Model.Cognome</label>
    <label>@Model.Alias</label>
    <label>@Model.Email</label>
    <label>@Model.Img</label>
    <label>@Model.NumeroTelefono</label>
@Html.ActionLink("Modifica","Edit","Contatto",new {IdContatto=@Model.IdContatto})
@Html.ActionLink("Elimina","Remove","Contatto",new {IdContatto=@Model.IdContatto})

Rubrica telefonica/Rubrica telefonica/Views/Contatto/Edit.cshtml
@model Rubrica_telefonica.Database.Contatto

<style>

        body {
  background-color: #cccccc !important;
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}

.contact-form-wrapper {
  padding: 100px 0;
}

.contact-form {
  padding: 30px 40px;
  background-color: white;
  border-radius: 12px;
  max-width: 400px;
}

.contact-form textarea {
  resize: none;
}

.contact-form .form-input,
.form-text-area {
  background-color: #ffffff;
  height: 50px;
  padding-left: 16px;
}

.contact-form .form-text-area {
  background-color: #ffffff;
  height: auto;
  padding-left: 16px;
}

.contact-form .form-control::placeholder {
  color: gray;
  font-weight: 500;
  opacity: 1;
}

.contact-form .form-control:-ms-input-placeholder {
  color: gray;
  font-weight: 500;
}

.contact-form .form-control::-ms-input-placeholder {
  color: red;
  font-weight: 500;
}

.contact-form .form-control:focus {
  border-color: #660000;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.07), 0 0 8px black;
}

.contact-form .title {
  text-align: center;
  font-size: 24px;
  font-weight: 500;
}

.contact-form .description {
  color: black;
  font-size: 14px;
  text-align: center;
}

.contact-form .submit-button-wrapper {
  text-align: center;
}

.contact-form .submit-button-wrapper input {
  border: none;
  border-radius: 4px;
  background-color: #b30000;
  color: white;
  text-transform: uppercase;
  padding: 10px 60px;
  font-weight: 500;
  letter-spacing: 2px;
}

.contact-form .submit-button-wrapper input:hover {
  background-color: dimgray;
}

    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <div>
  <div class="contact-form-wrapper d-flex justify-content-center">

    <form action="Edit" class="contact-form" method="post">

      <h5 class="title">Modifica contatto</h5>
      <p class="description">Inserire qui i dati del nuovo contatto
      </p>
      <div>
        <input type="hidden" class="form-control rounded border-white mb-3 form-input" name="IdContatto"   value="@Model.IdContatto" required>
        <input type="hidden" class="form-control rounded border-white mb-3 form-input" name="IdCellulare"   value="@Model.IdCellulare" required>
        <input type="hidden" class="form-control rounded border-white mb-3 form-input" name="IdPropietario"   value="@Model.IdPropietario" required>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Nome" placeholder="Nome"  value="@Model.Nome" required>
      </div>
       <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Cognome" placeholder="Cognome" value="@Model.Cognome" required>
      </div>
             <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Alias" placeholder="Alias" value="@Model.Alias" required>
      </div>
       <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Cellulare" placeholder="Cellulare"   maxlength="10" required>
      </div>
       <div>
        <input type="text" class="form-control rounded border-white mb-3 form-input" name="Fisso" placeholder="Fisso"  maxlength="10" >
      </div>
            <div>
        <input type="email" class="form-control rounded border-white mb-3 form-input" placeholder="Email" name="Email" value="@Model.Email" required>

      </div>
       
      <div class="submit-button-wrapper">
        <input type="submit" value="Edit">
      </div>
    </form>
  </div>
</div>

Rubrica telefonica/Rubrica telefonica/Views/Contatto/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Rubrica telefonica/Rubrica telefonica/Views/Home/Contatti.cshtml
@model List<Rubrica_telefonica.Database.Contatto>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Contatti";
    string jsonNumero = Accessor.HttpContext.Session.GetString("Numero");
    Numero num;
    if(jsonNumero!=null){
        num = Serializzazione.DeSerialize<Numero>(jsonNumero);
    }
}
@if(jsonNumero==null){
    // non loggato
    <div id="alreadylogged">
        <h1>Verrai reindirizzato al login</h1>
    </div>
    <script>
        $("#alreadylogged").ready(function() {
            setTimeout(window.location.href="@Url.Action("Index","Home")",3000)
    
        })

    </script>
}else{<script>
    $(document).ready(function() {
    $("#addContatto").click(function() {
    window.location.href="@Url.Action("Aggiungi","Contatto")"
})


})
    </script>
   <div class="container  mx-auto " name="page_container" style="transform:translateX(25%) ">
        <div class="row h-100 w-100" style="min-height:40px" >
            <!-- Container dei pulsanti principali (da fixare)-->
            <div class="col-lg-12 position-relative w-100 mb-2" name="barra_ricerca"  style="min-height:50px;min-width:150px">
                <input type="text" class="position-absolute top-0 start-0 rounded-4 w-50" style="min-height:35px;min-width:70px" placeholder="Cerca:"/>
                <button type="button" class="btn bg-transparent position-absolute end-50" id="search"><i class="bi bi-search"></i></button>
                <button type="button" class="btn btn-primary rounded-circle position-absolute start-50 top-0 ms-3" style="width:40px;height:40px"id="addContatto"><i class="bi bi-person-plus-fill fa-2x "></i></button>
            </div>
        </div>
        <div class="row w-50"  style="min-width:150px">
            <hr />
        </div>
        <hr />
        @foreach(var contatto in Model)
        {
@*         <div class="row"  onclick = "window.location.href='@Url.Action("Dettaglio", "Contatto",new{IdContatto=@contatto.IdContatto})'" >

*@  
    <div class="row"  onclick="loadDettaglio('@contatto.IdContatto')">
                       <div class="col-sm-1" name="immagine">
                    @if(contatto.Img!= null)
                    {
                        <img src ="@contatto.Img" title="immagine contatto">
                    }
                    else
                    {
                        <i class="bi bi-person"></i>
                    }
                </div>
                <div class="col-lg-11" name="nome">
                    @if (contatto.Alias != null && contatto.Alias.Trim()!="")
                    {
                        <p>@contatto.Alias</p>
                    }
                    else
                    {
                        <p>@contatto.Cognome @contatto.Nome</p>
                    }
                </div>
            </div>
        }
    </div>
    <div id="dettaglio" >

    </div>

        <script>


function loadDettaglio(IdContatto){

 
    
    $.get("/Contatto/Dettaglio?IdContatto="+IdContatto, function(data){
        $("#dettaglio").html(data)
    }
    )
   // $("#dettaglio").load("/Contatto/Dettaglio?IdContatto="+IdContatto)
}
    </script>

   
}

   

Rubrica telefonica/Rubrica telefonica/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
@{
    ViewData["Title"] = "Login";
    string idNumero = Accessor.HttpContext.Session.GetString("Numero");
    
        
    
    
}

@if(idNumero!=null){
    //già loggato
    <div id="alreadylogged">
        <h1>Verrai reindirizzato alla rubrica</h1>
    </div>
    <script>
        $("#alreadylogged").ready(function() {
            setTimeout(window.location.href="@Url.Action("Contatti","Home")",3000)
    
        })
    </script>
}else{
    //non loggato
    <div class="container  w-25 h-250 my-auto mx-auto" name="page_container">
        <div class="row w-100 text-center">
            <input type="text" id="numeroDiTelefono" class=" " placeholder="Telefono:" />
        </div>
         <div class="row pt-3 mx-auto  w-50 ">
             
            <button id="Login" class="btn btn-primary col-lg-12 w-75">Login</button>
             
        </div>
    </div>
    <script>
        $("#Login").click(function() {
            if ($("#numeroDiTelefono").val() != null && $("#numeroDiTelefono").val().trim() != "") { 
                $.ajax({
                    type: "post",
                    url: "@Url.Action("Login","Home")",
                    data: {
                        NumeroTelefono: $("#numeroDiTelefono").val()
                    },
                    dataType: "json",
                    success: function(data) {
                        window.location.href = "@Url.Action("Contatti","Home")"
                    }, error(req, status, error) {
                        console.log(error);
                        alert("Cannot contact databse");
                    }
                })
            }
        });
    </script>
}

Rubrica telefonica/Rubrica telefonica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rubrica_telefonica</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Rubrica_telefonica.styles.css" asp-append-version="true" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rubrica_telefonica</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                      <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contatto" asp-action="Aggiungi">Aggiungi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           @* &copy; 2022 - Rubrica_telefonica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>